steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ["-c","gcloud secrets versions access latest --secret=connector_secret >>./config/storj_config_test.json" ]
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/connector-mongodb', '.']
  - id: eclint
    name: "e53e225/editorconfig-checker"  
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]
  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint","run"]  
    env: ["GO111MODULE=on", "CGO_ENABLED=0"]
  - id: go_security
    name: "securego/gosec"
    args: ["./..." ] 
  - id: go_build
    name: "mirror.gcr.io/library/golang"
    env: ['GO111MODULE=on']
    args: ['go', 'build', './...']
  - id: doc_check
    name: "ubuntu"
    args: ['bash', './test/doc-check.sh']

tags: ['cloud-builders-community']
images: ['gcr.io/$PROJECT_ID/connector-mongodb']
tags: ['cloud-builders-community']
